import 'package:mobile_application_development/models/meal_log.dart';
import 'package:mobile_application_development/models/meal_food.dart';
import 'package:mobile_application_development/models/food.dart';
import 'package:mobile_application_development/repository/meal_repository.dart';
import 'package:mobile_application_development/repository/meal_food_repository.dart';
import 'package:mobile_application_development/repository/food_repository.dart';
import 'dart:developer' as developer;

class MealService {
  final MealLogRepository _repository;
  final MealFoodRepository _mealFoodRepository;
  final FoodRepository _foodRepository;

  MealService({
    required MealLogRepository repository,
    required MealFoodRepository mealFoodRepository,
    required FoodRepository foodRepository,
  })  : _repository = repository,
        _mealFoodRepository = mealFoodRepository,
        _foodRepository = foodRepository;

  /// Log a meal with multiple foods for a user
  /// Returns the created meal ID or null if failed
  Future<int?> logMeal({
    required int userId,
    required String mealType,
    required DateTime mealDate,
    required Map<int, Map<String, dynamic>> foodsWithQuantities,
  }) async {
    try {
      developer.log('🔵 MealService.logMeal START');
      developer.log('👤 User ID: $userId');
      developer.log('🍽️ Meal Type: $mealType');
      developer.log('📅 Meal Date: $mealDate');
      developer.log('📊 Foods Count: ${foodsWithQuantities.length}');

      // Validate inputs
      if (foodsWithQuantities.isEmpty) {
        throw Exception('No foods selected for meal');
      }

      if (userId <= 0) {
        throw Exception('Invalid user ID');
      }

      // Calculate total calories BEFORE creating the meal
      developer.log('💾 Calculating total meal calories...');
      double totalCalories = 0.0;

      try {
        // Fetch all foods once and create a map for quick lookup
        final allFoods = await _foodRepository.getFoodsByUser(userId);
        final foodMap = {for (var food in allFoods) food.foodId: food};
        developer.log('📚 Loaded ${foodMap.length} foods from database');

        if (foodMap.isEmpty) {
          developer.log('⚠️ WARNING: No foods found for user $userId');
          throw Exception('No foods found for user $userId');
        }

        for (final entry in foodsWithQuantities.entries) {
          final foodId = entry.key;
          final foodData = entry.value;
          final quantity = (foodData['quantity'] as num).toDouble();

          developer.log('🔍 Looking up food ID: $foodId');
          developer.log('   Quantity: $quantity grams');

          // Get food from cache
          final food = foodMap[foodId];

          if (food == null) {
            developer.log('❌ Food ID $foodId not found in user foods. Available IDs: ${foodMap.keys.toList()}');
            continue;
          }

          developer.log('✓ Found food: ${food.foodName}');
          developer.log('   Calories per 100g: ${food.caloriesPer100g}');

          // Calculate: (caloriesPer100g / 100) * quantity
          final foodCalories = (food.caloriesPer100g / 100.0) * quantity;
          totalCalories += foodCalories;

          developer.log('📝 ${food.foodName}: $quantity g × (${food.caloriesPer100g}/100) = ${foodCalories.toStringAsFixed(2)} kcal');
        }
      } catch (e) {
        developer.log('❌ Error calculating calories: $e');
        developer.log('❌ Stack trace: ${StackTrace.current}');
        // Continue anyway - we'll save the meal without total calories
        totalCalories = 0.0;
      }

      developer.log('✅ Total calculated calories: ${totalCalories.toStringAsFixed(2)} kcal');

      // Create the meal log entry with total calories
      final mealLog = MealLog(
        mealId: null, // Will be generated by database
        mealType: mealType,
        mealDate: mealDate,
        userId: userId,
        totalCalories: totalCalories > 0 ? totalCalories : null,
      );

      developer.log('💾 Creating meal log entry with calories...');
      developer.log('📊 MealLog data: ${mealLog.toJson()}');
      developer.log('📊 Total Calories before save: ${mealLog.totalCalories}');

      final createdMeal = await _repository.createMeal(mealLog);

      developer.log('✅ Meal created successfully with ID: ${createdMeal.mealId}');
      developer.log('✅ Returned total_calories from DB: ${createdMeal.totalCalories}');

      // Now save the foods for this meal
      if (createdMeal.mealId != null && createdMeal.mealId! > 0) {
        developer.log('💾 Saving ${foodsWithQuantities.length} foods to MealFood table...');

        final mealFoods = <MealFood>[];
        for (final entry in foodsWithQuantities.entries) {
          final foodData = entry.value;
          mealFoods.add(MealFood(
            mealFoodId: 0, // Will be generated by database
            mealId: createdMeal.mealId!,
            foodId: foodData['food_id'] as int,
            quantity: (foodData['quantity'] as num).toDouble(),
            unit: foodData['unit'] as String? ?? 'g',
          ));
        }

        try {
          await _mealFoodRepository.createMealFoods(mealFoods);
          developer.log('✅ All ${mealFoods.length} foods saved successfully to MealFood table');
        } catch (e) {
          developer.log('⚠️ Warning: Foods were not saved to MealFood table: $e');
          // Continue anyway - meal is already created
        }
      }

      return createdMeal.mealId ?? 0;
    } catch (e) {
      developer.log('❌ ERROR in MealService.logMeal: $e');
      developer.log('❌ Error Type: ${e.runtimeType}');
      rethrow;
    }
  }

  /// Get all meals logged by a user
  Future<List<MealLog>> getUserMeals(int userId) async {
    try {
      final meals = await _repository.getMealsByUser(userId);
      developer.log('Retrieved ${meals.length} meals for user $userId');
      return meals;
    } catch (e) {
      developer.log('Error in MealService.getUserMeals: $e');
      rethrow;
    }
  }

  /// Get a specific meal by ID
  Future<MealLog?> getMealById(int mealId) async {
    try {
      final meal = await _repository.getMealById(mealId);
      developer.log('Retrieved meal with ID: $mealId');
      return meal;
    } catch (e) {
      developer.log('Error in MealService.getMealById: $e');
      rethrow;
    }
  }

  /// Update an existing meal
  Future<MealLog> updateMeal({
    required int mealId,
    required String mealType,
    required DateTime mealDate,
    required int userId,
  }) async {
    try {
      final meal = MealLog(
        mealId: mealId,
        mealType: mealType,
        mealDate: mealDate,
        userId: userId,
      );

      final updatedMeal = await _repository.updateMeal(meal);
      developer.log('Meal updated via service: $mealId');
      return updatedMeal;
    } catch (e) {
      developer.log('Error in MealService.updateMeal: $e');
      rethrow;
    }
  }

  /// Delete a meal
  Future<void> deleteMeal(int mealId) async {
    try {
      await _repository.deleteMeal(mealId);
      developer.log('Meal deleted via service: $mealId');
    } catch (e) {
      developer.log('Error in MealService.deleteMeal: $e');
      rethrow;
    }
  }

  /// Calculate total calories for a meal based on its foods
  Future<double> calculateMealCalories(int mealId) async {
    try {
      developer.log('🔵 Calculating calories for meal $mealId');

      // Get all foods for this meal
      final mealFoods = await _mealFoodRepository.getMealFoodsByMealId(mealId);
      developer.log('📊 Found ${mealFoods.length} foods in meal');

      if (mealFoods.isEmpty) {
        developer.log('⚠️ No foods found for meal $mealId');
        return 0.0;
      }

      double totalCalories = 0.0;

      // For each food, get its calorie data and calculate
      for (final mealFood in mealFoods) {
        try {
          // Fetch the food details to get calories per 100g
          final foodList = await _foodRepository.getFoodsByUser(0);
          final food = foodList.firstWhere(
            (f) => f.foodId == mealFood.foodId,
            orElse: () => Food(
              foodId: 0,
              userId: 0,
              foodName: 'Unknown',
              category: 'Other',
              caloriesPer100g: 0.0,
              proteinPer100g: 0.0,
              carbsPer100g: 0.0,
              fatPer100g: 0.0,
            ),
          );

          // Calculate calories for this food based on quantity
          // Formula: (caloriesPer100g / 100) * quantity
          final caloriesForFood = (food.caloriesPer100g / 100.0) * mealFood.quantity;
          totalCalories += caloriesForFood;

          developer.log('📝 ${food.foodName}: ${mealFood.quantity}g = ${caloriesForFood.toStringAsFixed(1)} kcal');
        } catch (e) {
          developer.log('⚠️ Error calculating calories for food ${mealFood.foodId}: $e');
          // Continue with other foods
        }
      }

      developer.log('✅ Total meal calories: ${totalCalories.toStringAsFixed(1)} kcal');
      return totalCalories;
    } catch (e) {
      developer.log('❌ Error in calculateMealCalories: $e');
      return 0.0;
    }
  }

  /// Get meal with calculated calories
  Future<Map<String, dynamic>> getMealWithCalories(int mealId) async {
    try {
      final meal = await _repository.getMealById(mealId);
      final calories = await calculateMealCalories(mealId);

      return {
        'meal': meal,
        'calories': calories,
      };
    } catch (e) {
      developer.log('Error in getMealWithCalories: $e');
      rethrow;
    }
  }
}


